### ISSUE TITLE
Add fork

### ISSUE THREAD

**Issue by bobiblazeski** [bobiblazeski/Q#3]
``` javascript
var fork = R.curry(function(lastly, f, g, x) {
    return lastly(f(x), g(x));
});

var avg = fork(R.divide, R.sum, R.length); // change this
avg([1,2,3,4,5])); // => 3
```

**Comment by davidchambers** [comment]
`fork` already exists: see [`R.converge`](http://ramdajs.com/docs/#converge). :)

**Comment by bobiblazeski** [comment]
Great, I'm surprised how much ground does ramda cover.
Why converge instead of fork?

**Comment by davidchambers** [comment]
> Why converge instead of fork?

You'd need to ask @buzzdecafe or @CrossEye. The function both forks and converges, though, so both names are suitable.

**Comment by buzzdecafe** [comment]
because we want to dispatch to `Future` ADT on `fork`

**Comment by bobiblazeski** [comment]
@davidchambers @buzzdecafe Is there support for other forks and hooks beside monadic fork?

Monadic  noun fork in particular.

``` javascript
var monadicNounFork = R.curry(function monadicNounFork(fn1, fn2,arg1, arg2){
    return fn1(fn2(arg1),arg2);
});
var listPlus = monadicNounFork(R.map, R.add);
console.log(listPlus(10, [1,2,3,4,5]));
```

http://www.jsoftware.com/help/jforc/forks_hooks_and_compound_adv.htm
http://www.jsoftware.com/help/learning/09.htm

**Comment by buzzdecafe** [comment]
we've reserved fork for dispatching to [`Future` types](https://github.com/folktale/data.task/blob/ee7899662127fa5c6908a2bd9f7d598fd63a8203/lib/future.js), but it's not clear to me what `fork` should do in list context. I'll take a look at those links, maybe inspiration will strike.

**Comment by bobiblazeski** [comment]
List context? Forks & hooks are best for point free programming, which J is best at. Will make some uses later.

**Comment by buzzdecafe** [comment]
i am looking at it from the other direction. Since we want to dispatch to `Future.fork`, how would the semantics of `Future.fork` apply to a list? Much as we dispatch on `map` because `Functor` behavior is well-defined for many types.
